### ISSUE TITLE
fieldname instead of classname in generated code

### ISSUE THREAD

**Issue by RainerTSI** [esnacc/esnacc-ng#28]
I have an asn-file which defines (ampng others) a sequence named  ChannelMask-64k from a subcontractor. The sequence has a field named channelMask64k. The code generated from this definition (c++ backend) has an error in the ChannelMask64k class. One constructor is generated with the wrong name channelMask64k (first letter is lower case instead of upper case):

class ChannelMask64k: public AsnBits {
  public:
    ChannelMask64k (const char *stringFrom=NULL):AsnBits(stringFrom){ }
    channelMask64k (size_t numBits):AsnBits(numBits) { }           //  <---- ERROR

I can generate the right code with the following change in the file  cxxmultipleconstraints.c (from compiler/back-ends/c++-gen). at line 986;

from
 fprintf(hdr, "          %s (size_t numBits):AsnBits(numBits) { }\n", e->type->cxxTypeRefInfo->fieldName);
to
 fprintf(hdr, "          %s (size_t numBits):AsnBits(numBits) { }\n", className);

The use of the fieldName instead of the classname in the generation of a block of constructors looks like an error. At least this patch solved my problem. Please check if this change is OK.

**Comment by orgcandman** [comment]
Excellent catch. It is a bug.
I can spin up a patch, or can take one from you. If you submit one, please include an appropriate 'Signed-off-by' line.

**Comment by RainerTSI** [comment]
Thanks for the quick response. I think it is easier if you create a patch.
