### ISSUE TITLE
Strange result from PEnc()

### ISSUE THREAD

**Issue by crw4096** [esnacc/esnacc-ng#34]
Hi,

I'm experimenting with esnacc and have run across what looks like a bug.  The basics are that when I use BEnc() to encode a million samples, I get a sensible number of bytes.  But when use PEnc(), the result is always 8.  See attached ZIP file below.

The esnacc version is kind of old, but I do plan to update.  The program reports "Version 1.6, Release Date: AUG-29-2003" :-(

Charles

[asn1.zip](https://github.com/esnacc/esnacc-ng/files/376865/asn1.zip)

**Comment by orgcandman** [comment]
Currently, PER is 'experimental' - and the encoders are not being properly hooked up.  This goes for the C and C++ back-ends.  I was hoping to get time to work on PER, UPER, XER, JSER, and GSER.  Those will have to be done piecemeal.  I'll leave this open, though.

Thanks for the report, and a good test-case.

**Comment by crw4096** [comment]
Thanks.  If it matters, I'd prefer to see PER as a higher priority than the others, not that I know anything about them, except perhaps that XER.  Anyway, glad to know it's not me :)

**Comment by momor10** [comment]
is this already fixed? is uper supported? if not, where is the per code to find, it may be not hard to change add uper support if its similar.
