### ISSUE TITLE
Compiling from Debian package

### ISSUE THREAD

**Issue by gregarican** [esnacc/esnacc-ng#36]
I read through the **INSTALL.md** file and followed the instructions carefully. But still no luck. 

First, I installed **build-essential**, **cdbs**, **dh-autoreconf**, and **fakeroot** via **_apt-get install_**. Then I added these four items to the **./debian/control** file's **_Build-Depends_** line. When I ran **_dpkg-checkbuilddeps_** I saw no printed error messages.

When I then ran **_fakeroot debian/rules binary_**, I received the error listed below. Any suggestions about what to do? I ensured that the **esnacc.dirs** file exists and that its permissions grant access. That looks okay. 

`root@raspberrypi:/home/pi/esnacc-ng-master# fakeroot debian/rules binary
dh binary --with autoreconf
   dh_installdirs
/home/pi/esnacc-ng-master/debian/esnacc.dirs: 1: /home/pi/esnacc-ng-master/debian/esnacc.dirs: usr/bin: not found
dh_installdirs: problem reading debian/esnacc.dirs:
debian/rules:6: recipe for target 'binary' failed
make: *** [binary] Error 127` 

I changed this to be **/usr/bin** (which exists). but now I receive a permission denied error.

`root@raspberrypi:/home/pi/esnacc-ng-master# fakeroot debian/rules binary
dh binary --with autoreconf
   dh_installdirs
/home/pi/esnacc-ng-master/debian/esnacc.dirs: 1: /home/pi/esnacc-ng-master/debian/esnacc.dirs: /usr/bin: Permission denied
dh_installdirs: problem reading debian/esnacc.dirs:
debian/rules:6: recipe for target 'binary' failed
make: *** [binary] Error 126`

I checked and can see that ./debian/rules has rwx permissions. So I am at a loss. It must be something simple I am overlooking? Forgive me for my shortsightedness, as I used to be old school command line Linux back around 1997-2000, but haven't delved into this area is awhile :)

**Comment by gregarican** [comment]
Just to ensure this was a clean unzipped source directory, I wiped it out and extracted it directly from my Linux host. Previously I extracted the directory using my Windows host and copied it over to my Linux host. Just in case there was any funkiness going on.

Using this fresh source directory I went through the same steps to install from a Debian package. Below is  a snippet from the tail end of my _**fakeroot debian/rules binary**_ routine. 

`novalid -o compiler/esnacc.1 http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl compiler/esnacc.xml
/bin/bash: novalid: command not found
Makefile:4567: recipe for target 'compiler/esnacc.1' failed
make[3]: [compiler/esnacc.1] Error 127 (ignored)
 /bin/mkdir -p '/home/pi/esnacc-ng-master/debian/tmp/usr/share/man/man1'
 /usr/bin/install -c -m 644 ./compiler/esnacc.1 '/home/pi/esnacc-ng-master/debian/tmp/usr/share/man/man1'
/usr/bin/install: cannot stat `./compiler/esnacc.1': No such file or directory
Makefile:3771: recipe for target 'install-man1' failed
make[3]: *** [install-man1] Error 1
make[3]: Leaving directory '/home/pi/esnacc-ng-master'
Makefile:4284: recipe for target 'install-am' failed
make[2]: *** [install-am] Error 2
make[2]: Leaving directory '/home/pi/esnacc-ng-master'
Makefile:4278: recipe for target 'install' failed
make[1]: *** [install] Error 2
make[1]: Leaving directory '/home/pi/esnacc-ng-master'
dh_auto_install: make -j1 install DESTDIR=/home/pi/esnacc-ng-master/debian/tmp AM_UPDATE_INFO_DIR=no returned exit code 2
debian/rules:6: recipe for target 'binary' failed
make: *** [binary] Error 29
root@raspberrypi:/home/pi/esnacc-ng-master# `

I'm thinking something might be missing from my machine, perhaps a build dependency or something? If this is the wrong forum to the posting my issues please let me know. Since perhaps this thread is best suited for the project page rather than the code repo?

**Comment by orgcandman** [comment]
Thanks for the report. Please subscribe to the bugs list (on mail.esnacc.org) and report your issue there. I'll try to reproduce in the next 7 days and update you.

**Comment by gregarican** [comment]
I had to add a few extra Debian packages. And was able to get things to install. Although I'm having separate issues using the final product to compile some CSTA ASN1 elements into C. That's another story for another forum :)

If anyone is interested, here's a link to a RAR of the three Debian packages that I know worked for me. This is compatible with Raspberry Pi type distros. Hope this helps someone else out there!

[https://dl.dropboxusercontent.com/u/61224429/esnacc_1.80_debianpkg_raspberry_pi.rar](https://dl.dropboxusercontent.com/u/61224429/esnacc_1.80_debianpkg_raspberry_pi.rar)

**Comment by orgcandman** [comment]
What did you have to do? It would be good to know so that we can update the documentation.

**Comment by orgcandman** [comment]
Please respond - the information you've posted regarding .dirs files goes directly against the debian manual.

**Comment by gregarican** [comment]
Please remove the comment then. I was attempting to compile an old CSTA program that was circa 2001 or so. Using newer compilers and whatnot it was a rat’s nest. So I moved on since it wasn’t a production-critical program I was working on. Thanks anyway!

Greg Kujawa
IT Manager

DIAMOND CELLAR Holdings, LLC
6280 Sawmill Road
Dublin, OH 43017
614-923-9515 phone
614-336-4555 fax
www.diamondcellar.com<http://www.diamondcellar.com>
Office Hours: M Tu W Th F

[cid:image002.png@01CF8981.56A564A0]<https://www.facebook.com/DiamondCellar>[cid:image003.png@01CF8981.56A564A0]<https://twitter.com/DiamondCellarCo>[cid:image004.png@01CF8981.56A564A0]<http://www.pinterest.com/diamondcellar/>[cid:image005.png@01CF8981.56A564A0]<http://www.yelp.com/biz/diamond-cellar-dublin>[cid:image006.png@01CF8981.56A564A0]<http://instagram.com/diamondcellar>[cid:image007.png@01CF8981.56A564A0]<https://plus.google.com/+DiamondCellarDublin/about>


CONFIDENTIALITY NOTICE
UNAUTHORIZED INTERCEPTION IS PROHIBITED BY FEDERAL LAW
[Electronic Communications Privacy Act of 1986, 18 U.S.C. 2701(a) and 2702(a)] This message is protected by Constitutional Rights and applicable legal privileges.  It is strictly confidential.
