### ISSUE TITLE
Are examples actually built?

### ISSUE THREAD

**Issue by mouse07410** [esnacc/esnacc-ng#38]
There are several subdirectories (`tcl-example`, `tbl-example`, `cxx-examples`, `c-examples`) that contain source files, `automake.mk`, and/or `readme`. But those sources cannot be compiled following the given instructions.

Are they defunct? Am I supposed to be able to build those?

Would appreciate some guidance.

Also, from `FAQ.md` it wasn't clear to me what's the actual current status of DER support. Is everything that's BER-encodable (in C and C++) also DER-encodable? I'm asking because I need all my encoding to be DER rather than BER... How/where do I check for this?

Thanks!

**Comment by orgcandman** [comment]
The examples are built - but only when using `make check`.

For your second question, I'll update the FAQ. We usually encode things in such a way that they are both DER and BER - however, I don't know where, specifically, we vary - it could be in `CHOICE` processing.  I'll look into this.

**Comment by mouse07410** [comment]
Thank you! Looking forward for FAQ and docs update.

**Comment by mouse07410** [comment]
I guess there's no reason to keep this issue open - I trust that you will update the FAQ in reasonable time. :-)
