### ISSUE TITLE
c-lib/inc/asn-config.h wants config.h, which is not installed

### ISSUE THREAD

**Issue by mouse07410** [esnacc/esnacc-ng#39]
I've installed the current github master version of esnacc-ng. However the installation does not seem complete:
```
$ cat Test.asn1
TEST DEFINITIONS ::= BEGIN

Test ::= SEQUENCE
{
    foo [0] SEQUENCE OF INTEGER,
    --bar [1] SEQUENCE OF INTEGER 
    --bar [1] SEQUENCE OF INTEGER (0..4294)
    bar [1] SEQUENCE OF INTEGER (0..4294967295)
    --bar [1] SEQUENCE OF INTEGER (0..429496729)
}
END
$ esnacc Test.asn1 
$ clang -o Test.o -c Test.c -I/opt/local/include/c-lib/inc -I/opt/local/include/c-lib
In file included from Test.c:8:
In file included from ./Test.h:2:
In file included from /opt/local/include/c-lib/inc/asn-incl.h:86:
/opt/local/include/c-lib/inc/asn-config.h:105:10: fatal error: 'config.h' file not found
#include "config.h"
         ^
1 error generated.
$ 
```

File `config.h` located in the root directory of `esnacc-ng` does not get installed with the rest of the include files, but appears to be required by them. This applies to the other .h files from the esnacc-ng root directory.

Is there any reason why they aren't installed in `c-lib/inc`?

P.S. I did not observe the same problem with `cxx-lib`:
```
$ esnacc -C Test.asn1 
$ clang++ -o Test.o -c Test.cpp -I/opt/local/include/cxx-lib/inc -I/opt/local/include/cxx-lib
Test.cpp:118:13: warning: equality comparison with extraneous parentheses
      [-Wparentheses-equality]
  if ((tag1 == MAKE_TAG_ID (CNTX, CONS, 0)))
       ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Test.cpp:118:13: note: remove extraneous parentheses around the comparison to silence this
      warning
  if ((tag1 == MAKE_TAG_ID (CNTX, CONS, 0)))
      ~     ^                             ~
Test.cpp:118:13: note: use '=' to turn this equality comparison into an assignment
  if ((tag1 == MAKE_TAG_ID (CNTX, CONS, 0)))
            ^~
            =
Test.cpp:140:13: warning: equality comparison with extraneous parentheses
      [-Wparentheses-equality]
  if ((tag1 == MAKE_TAG_ID (CNTX, CONS, 1)))
       ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Test.cpp:140:13: note: remove extraneous parentheses around the comparison to silence this
      warning
  if ((tag1 == MAKE_TAG_ID (CNTX, CONS, 1)))
      ~     ^                             ~
Test.cpp:140:13: note: use '=' to turn this equality comparison into an assignment
  if ((tag1 == MAKE_TAG_ID (CNTX, CONS, 1)))
            ^~
            =
2 warnings generated.
$
```

**Comment by orgcandman** [comment]
Thanks for reporting this.  I'll try and cook up some patches, but I'm currently traveling at OVSConf2016

**Comment by mouse07410** [comment]
Thanks! No rush, as long as you're keeping track of this. ;-)

**Comment by orgcandman** [comment]
Please try the patch at http://mail.esnacc.org/pipermail/dev/2016-November/000063.html and see if that works for you.

**Comment by mouse07410** [comment]
That patch helped - but not completely:
```
$ clang -I/opt/local/include/c-lib/inc -c Test.c
In file included from Test.c:8:
In file included from ./Test.h:2:
In file included from /opt/local/include/c-lib/inc/asn-incl.h:86:
In file included from /opt/local/include/c-lib/inc/asn-config.h:105:
/opt/local/include/c-lib/inc/snacc.h:75:10: fatal error: 'config.h' file not found
#include "config.h"
         ^
1 error generated.
$
```

**Comment by orgcandman** [comment]
Yeah, I missed snacc.h, so I'll repost a patch, soon.

**Comment by mouse07410** [comment]
`snacc.h` decides whether to pull other include files based on the defines provided by `config.h`. I see only three alternatives here:

1. You just add `config.h` to the set of include files installed in `.../c-lib/inc/` (by the way, why can't it be `.../c-lib/`? Why that extra `inc/`?).
2. To avoid any possible file name collision, you rename `config.h` to something like `esnacc-ng-config.h`. You still copy it to `.../c-lib/inc/` like in (1).
3. You create and fill `snacc.h`as a part of your build process, adding the appropriate `#include <memory.h>` and such based on whether the configuration located them on the target machine, or not. Probably the nicest solution - but definitely the most labor-intensive (and I'm not sure this effort would be justified).

@orgcandman which alternative from the above you choose? (Or did I miss another possible solution?)

**Comment by orgcandman** [comment]
The first two are not viable. I'll get back to this next week, but am flying today. Thanks for your help.

**Comment by mouse07410** [comment]
Thanks! I tried your patch and it appears to be working - except that it didn't seem to copy/install `snacc.h` to `$PREFIX/c-lib/inc/` destination directory.

**Comment by orgcandman** [comment]
I've applied the patch.  Not sure about the `snacc.h` issue, but that seems to be some kind of autotools issue.

Thanks for your help, Uri!

**Comment by mouse07410** [comment]
Sure, thanks!
