### ISSUE TITLE
Some .h files not getting installed

### ISSUE THREAD

**Issue by mouse07410** [esnacc/esnacc-ng#40]
@orgcandman I'm not sure it's just autotools issue - we need to figure out why the following files are not getting installed by `make clean && make all && make check && sudo make install`:

1. ~~`c-lib/inc/policy.h`~~ *Update: not actually used*
2. `c-lib/inc/snacc.h`        *Update:* ***must*** *be installed* 
3. ~~`c-lib/inc/version.h`~~  *Update: not actually used*

**Update**
Re-initialize autotools via something like `autoreconf -i` does not help. These files still don't get installed. I know that `snacc.h` must be installed, haven't checked how necessary the other two are.

**Comment by mouse07410** [comment]
To be more specific: after a successful installation of the current github master esnacc-ng, I observe that the following files require `snacc.h` (which is not being installed):

- `asn-config.h` (line 105)
- `mem.h`  (line 50)

**Comment by orgcandman** [comment]
I don't see c-lib/inc/policy.h, but I do see a policy.h in the root.  This is not being installed, so I'll submit a patch.

I do see snacc.h being installed (see the attached typescript file) already, and with the patch I'm proposing, policy.h should be installed as well.

**Comment by orgcandman** [comment]
Ugh - so it couldn't upload.  See http://aaron.bytheb.org/files/typescript (made with `script` utility)

**Comment by mouse07410** [comment]
> I do see snacc.h being installed (see the attached typescript file) already...

And on Mac OS X I consistently do **not** see the file `snacc.h` installed, on two different machines - one running 10.11.6 El Capitan, the other one running 10.12.1 Sierra.

**Comment by orgcandman** [comment]
Is there a possible security constraint you are encountering?  Does this happen even if you use a completely unknown prefix (I tried with /tmp/issue40)?

**Comment by mouse07410** [comment]
> Is there a possible security constraint you are encountering?

On both machines that are under different policies, running different versions of Mac OS, and trying to access non-privileged (outside of SIP) directory?

I find it **highly** unlikely, especially considering that it successfully installs everything else.

**Comment by orgcandman** [comment]
are you looking for snacc.h to be located in c-lib/inc?  It's currently installed in the 'root' include directory (so if your prefix is /usr, it will be in /usr/include/snacc.h).  This is because snacc.h is used by c++ and c libraries.  Is that the source of confusion here?  I'm trying to understand the behavior difference we're seeing.

**Comment by mouse07410** [comment]
> are you looking for snacc.h to be located in c-lib/inc?

Hmm, yes, of course! 

In my opinion, the correct way would be to install everything (all the include files) in `${PREFIX}/include/c-lib/` for C include files, and `${PREFIX}/include/cxx-lib/` for C++ include files. Then all of your (generated) code should do `#include <c-lib/snacc.h>`, `#include <c-lib/asn-config.h`, etc. 

The way it is now - the poor user has to provide a truckload of `-I` flags to work with esnacc.

A normal expected way is to let user list just one additional include directory, in my case `-I/opt/local/include`. And everything I compile needs just that - OpenSSL sources know to look for `<openssl/whatever.h>`, Crypto++ looks for `<cryptopp/whatever.h>`, etc. Everything works nicely.

But for esnacc - not enough, I have to add `-I/opt/local/include/c-lib/inc`. But on top of that unnecessary inconvenience, it pollutes the main directory, installing `snacc.h` there!

I strongly suggest to re-think and change this behavior.

**Comment by orgcandman** [comment]
Okay - it makes sense, and I am all for it.  We do use pkg-config to provide for build integration (with things like autotools), so for example:

  pkg-config libesnacc --cflags --libs

provides the appropriate flags.  I understand that this is only one method of doing this.

Your proposed restructure is okay by me, but it would break existing users, and has existed that way for a while now (at least now they get segregated - previously all of the headers were installed into /usr/include).  I'm okay duplicating this into both c-lib/inc and cxx-lib/inc, but it requires learning a bit more autotools than I have time to do now.  If you can write the patches for it and post them to dev@lists.esnacc.org I will gladly take a look and install.  Especially if they can keep users from being broken.

**Comment by mouse07410** [comment]
The main idea is to avoid forcing users to add "-I${PREFIX}/c-lib/inc" to their compilation.

One way to accomplish this is changing how the generated files look. Example:
```
TEST DEFINITIONS ::= BEGIN

Test ::= SEQUENCE
{
    foo [0] SEQUENCE OF INTEGER,
    bar [1] SEQUENCE OF INTEGER (0..4294967295),
    ...
}
END
```
Currently the produced `Test.h` file begins with
```

#include "asn-incl.h"
/*
 *    Test.h
 *    "TEST" ASN.1 module C type definitions and prototypes
 *    This file was generated by esnacc on Mon Nov 14 15:33:25 2016
 *    NOTE: This is a machine generated file--editing not recommended
 */

#ifndef Test_h_h
#define Test_h_h

. . . . .
```

What in my opinion it should look like is
```
/*
 *    Test.h
 *    "TEST" ASN.1 module C type definitions and prototypes
 *    This file was generated by esnacc on Mon Nov 14 15:33:25 2016
 *    NOTE: This is a machine generated file--editing not recommended
 */

#ifndef Test_h_h
#define Test_h_h

#include <c-lib/inc/asn-incl.h" // or #include <c-lib/asn-incl.h>

. . . . .
```

Note also that the first "actionable" line should be *after* `#ifndef Test_h_h/#define Test_h_h` instead of being stuck *before* it.

**Comment by orgcandman** [comment]
So, I've started in on this refactor.  Patch 1/2 is okay.  Patch 2/2 could be considered 'complete', and submitted with a 3rd patch added cleaning up the c-lib and cxx-lib includes.  However, this is more work than I can sign up for at the moment. Is it possible for you to take on the rest of the work?  It's all in the repo / branch listed.

https://github.com/orgcandman/esnacc-ng/tree/refactor_headers

**Comment by mouse07410** [comment]
> Is it possible for you to take on the rest of the work?

I'd need to request and obtain permission for participating - which could take time (and it isn't certain that I would get it). :-(

**Comment by orgcandman** [comment]
Well, it still might be faster for you to do that - I've got some other work I have to prioritize for the next few weeks, so my esnacc contributions will have to be cut back for a while.

Is this issue so pressing that you can't move forward or does the workaround satisfy for now?

**Comment by mouse07410** [comment]
The issue can wait (not pressing now). I'll see what I can do. In the meanwhile, if by the time you're more free it is not done (i.e., I didn't manage) - feel free to do it.

**Comment by orgcandman** [comment]
Please try out the patches at http://patchwork.esnacc.org/bundle/esnaccroot/change-api/?series=&submitter=&state=5&q=&archive= and see if they work for you :)

**Comment by orgcandman** [comment]
I've pushed a developed version of the series found above.

Thanks, Uri

**Comment by mouse07410** [comment]
Great conclusion!! Thank you!
