### ISSUE TITLE
Compiling from Debian - missing dependency

### ISSUE THREAD

**Issue by konradb81** [esnacc/esnacc-ng#44]
Hi,

When I tried to compile esnac on debian environment, i spotted an error:

novalid -o compiler/esnacc.1 
/bin/bash: novalid: command not found 
...

This situation appears when $(XSLTPROC) variable is empty during compilation process (XSLTPROC=''). 

In debian you need package xsltproc (apt-get install xsltproc) in order to be able to properly compile sources, but info about this dependency is missing in INSTALL.md

I only share information on how to bypass the problem,

Best regards, KB

**Comment by orgcandman** [comment]
Thanks for the report.  I'll send a patch to the mailing list soon.  Can you send me your name + email if you want it to appear in the AUTHORS file?

**Comment by konradb81** [comment]
Thanks, but it is not necessary :) - i only want to help others :)

Thanks and best regards!
Konrad

**Comment by orgcandman** [comment]
Thanks for your contribution, @konradb81
