### ISSUE TITLE
MinBuf not updating pointers

### ISSUE THREAD

**Issue by m-cobbold** [esnacc/esnacc-ng#45]
When I'm attempting to use the MinBuf, I'm finding that the pointer is not being decremented after data is added to the buffer.

**Comment by orgcandman** [comment]
Thanks for the report.  Can you give a small test case?  Which version of esnacc are you using?

**Comment by m-cobbold** [comment]
I've zipped up the test code along with the asn1 file and a bash script to build it. Basically it should encode the data and output the result to the terminal. The expected result should be  0x30 0x06 0x02 0x01 0x12 0x02 0x01 0x30

I'm using the current trunk version of esnacc on Ubuntu.

[TestModule.zip](https://github.com/esnacc/esnacc-ng/files/1689889/TestModule.zip)

I've patched  `MinBufPutSegRvs__ ` on my local version by adding `*(unsigned char **)b = dst;` which seems to have fixed it for me.

**Comment by m-cobbold** [comment]
Just to note, there's an error in the generated header file when compiling for c. It generates
`#ifdef __cplusplus
extern "C" {
#endif`
at both the top and bottom of the generated header instead of 
`#ifdef __cplusplus
}
#endif`
at the bottom. The min-buf.h file is also missing the extern C markup

**Comment by orgcandman** [comment]
Thanks for this report!  I'll get fixes ready.

**Comment by orgcandman** [comment]
I think this is fixed in branch-1.8 and master now.  Thanks for the report.
