### ISSUE TITLE
SNACC ExpBuf bugs

### ISSUE THREAD

**Issue by Josie-H** [esnacc/esnacc-ng#9]
Thought I ought to make you aware of some problems with SNACC's (C-lib) ExpBufs, since finding them in our company's own branch of SNACC. (I've checked, and they're still present in yours.)

The basic idea of ExpBufs is that there’s a chain of 1024-byte blocks of memory. The thing the original author failed to consider is that there’s a difference between leaving the “current” pointer at the end of one block at the end of an operation, and leaving it at the beginning of the next – they leave it on different sides after reading and after writing. So a write then a write (or a read then a read) will always be fine, but doing one then the other will fail if the first ends on a 1024-byte boundary. (I’ve only fixed this one way round in our codebase, since we only ever write then read everything back.)

The effect of this to the outside world is that when you try to compose an ASN.1 message that should be a multiple of 1024 bytes, you'll get back something that has the correct length but not necessarily the correct contents.

The right fix is probably to make sure that the "current" pointer ends up in a consistent place after all operations that end on a boundary. My fix for our codebase is less right and more quick, so I won't include it here!

(Bug also submitted to Ubuntu's SNACC package: https://bugs.launchpad.net/ubuntu/+source/snacc/+bug/1537085)

**Comment by orgcandman** [comment]
Wow, thanks for the excellent writeup. I've been in that area a bit recently (you've probably noticed there are _epic_ amounts of memory leaks present in the original sources, so I urge you to pull the changes that have been put in), and thought something wasn't looking right. I have plans during Feb to address some of the outstanding issues, so I'll look into this closely.

Again, thanks for the awesome write up.

**Comment by Josie-H** [comment]
No problem.

I had noticed that when you go over 1024 bytes, going into write mode doesn't automatically free the whole expanded buffer like it does under 1024, but I wasn't sure whether that was a bug in SNACC or just our codebase expecting too much of it!

I'll probably have to punt the majority of this bug over to our dev team (I'm a Support engineer myself these days) but I'll recommend that they check out this project when they look at it.

**Comment by orgcandman** [comment]
Cool. If you could also post a sample that triggers the issue easily that would be helpful, too. Thanks again.

**Comment by Josie-H** [comment]
I've got nothing that isn't massively tied up to the rest of our code, I'm afraid.  (And probably technically company rules forbid me from posting that anyway!)  But should be fairly easy to repro: just create an ExpBuf with default portion length, write in 1024 bytes, try to read them again.  (Write-read bug.)  And create an ExpBuf, write 1028 bytes, read 4 bytes, try to write more.  (Read-write bug, though I haven't tested that one.)  And for the memory-growing one, just create an ExpBuf, write in 1028 bytes, "reset for writing", and check that the buffer still has a non-NULL prev field.  (The more I think about that one, the more I reckon it is a genuine bug, since "resetting" does drop some data in the buffer, just not all of it.)

**Comment by orgcandman** [comment]
I just merged a pull request which I think may fix this issue - but note that it includes HUGE amounts of refactoring as well. Is it possible to try out this version and see if it fixes your expbuf issues? If not, let me know.

**Comment by Josie-H** [comment]
I'll put a note about this in the relevant in-company bug report, but it'll likely be quite a while before anyone looks at it, since I patched our immediate problem.  Thanks for the heads-up though!

**Comment by orgcandman** [comment]
Sorry for the late work on this - I've just posted a patch series to the list that I believe addresses these issues.  Can you please check the series at:
http://mail.esnacc.org/pipermail/dev/2016-December/000109.html

If it works, please send an Acked-by: tag (either to the list, or in this issue) and I'll merge+close

**Comment by mouse07410** [comment]
@orgcandman I tried to look up your proposed fixes, but failed. IMHO it would make sense to submit them as a PR, which (if it works) you or others could then merge.

**Comment by orgcandman** [comment]
@mouse07410 I'll work on a solution that lets us keep the email system.  I like DCO based development - it means everyone (ostensibly) understands the licensing restrictions / obligations, and there's a digital stamp of approval (Signed-off-by, Acked-by, etc.)

In the meantime, you can look at the core changes at https://github.com/orgcandman/esnacc-ng

Thanks for taking a look.

**Comment by orgcandman** [comment]
I've applied the series referenced in the above.  If the issues persist, please let me know.

Thanks.
